# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kLlhrAfxE8KHmTg6XDZYPXG3mmozWZF6
"""

def calcular_area(largo, ancho):
    return largo * ancho

def calcular_perimetro(largo, ancho):
    return 2 * (largo + ancho)


largo = 10
ancho = 5

print("Área:", calcular_area(largo, ancho))
print("Perímetro:", calcular_perimetro(largo, ancho))